apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-deployment
  labels:
    app: delivery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-service
      app.type: microservice
  template:
    metadata:
      labels:
        app: delivery-service
        app.type: microservice
      annotations:
        sidecar.opentelemetry.io/inject: "otel-collector"
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
        - name: delivery-service
          image: docker.host.internal:5000/delivery:latest
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: ADDRESS_VALIDATION_SERVICE_URL
              value: http://address-validation-service:8080
            - name: GERONIMO_METRICS_JAXRS_ACCEPTEDHOSTS
              value: prometheus-kube-prometheus-stack-prometheus-0
            - name: GERONIMO_METRICS_JAXRS_ACCEPTED_HOSTS
              value: prometheus-kube-prometheus-stack-prometheus-0
