services:
  authentication-ui:
    image: nginx:1.27.1
    ports:
      - "6060:8080"
    volumes:
      - ./authentication-ui/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./authentication-ui/static:/var/www
    environment:
      - CODESPACE_HOST=${CODESPACE_NAME}-6060.app.github.dev
    command: /bin/bash -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'" 

  customer-service:
    build: customer-service/
    ports:
      - "4000:8080"
    environment:
      - BILLING_SERVICE_URL=http://billing-service:8080
      - DELIVERY_SERVICE_URL=http://delivery-service:8080

  billing-service:
    build: billing-service/
    ports:
      - "4001:8080"

  delivery-service:
    build: delivery-service/
    ports:
      - "4002:8080"
    environment:
      - ADDRESS_VALIDATION_SERVICE_URL=http://address-validation-service:8080

  address-validation-service:
    build: address-validation-service/
    ports:
      - "4003:8080"

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    container_name: keycloak
    command: "start-dev"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
    ports:
      - "9191:8080"
    volumes:
      - ./keycloak/:/opt/keycloak/data/h2/
