services:
  swagger-ui:
    image: swaggerapi/swagger-ui:v5.17.7
    volumes:
      - "./swagger-ui:/usr/share/nginx/html/doc"
    environment:
      API_URL: "doc/openapi.yaml"
  wiremock:
    image: wiremock/wiremock:3.5.4
    volumes:
      - "./wiremock:/home/wiremock"
    ports:
      - "7070:8080"
  hurl:
    image: ghcr.io/orange-opensource/hurl:4.3.0
    command: "--retry 5 --test /home/address-1.0.hurl /home/address-1.1.hurl /home/address-2.0.hurl"
    volumes:
      - "./hurl:/home"
    depends_on:
      - wiremock
  api-gateway:
    image: nginx:1.27.1
    ports:
      - "6060:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
