services:
#  gateway:
#    image: nginx:1.27.1
#    ports:
#      - "9090:8080"
#    volumes:
#      - ./gateway/nginx.conf:/etc/nginx/nginx.conf

  customer-service:
    build: customer-service/
    container_name: customer-service
    ports:
      - "4000:8080"
    environment:
      - BILLING_SERVICE_URL=http://billing-service:8080
      - DELIVERY_SERVICE_URL=http://delivery-service:8080
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=console
      - OTEL_LOGS_EXPORTER=console
      - OTEL_METRIC_EXPORT_INTERVAL=10000
    networks:
      - api-design

  billing-service:
    build: billing-service/
    container_name: billing-service
    ports:
      - "4001:8080"
    networks:
      - api-design

  delivery-service:
    build: delivery-service/
    container_name: delivery-service
    ports:
      - "4002:8080"
    environment:
      - ADDRESS_VALIDATION_SERVICE_URL=http://address-validation-service:8080
    networks:
      - api-design

  address-validation-service:
    build: address-validation-service/
    container_name: address-validation-service
    ports:
      - "4003:8080"
    networks:
      - api-design

  jaeger:
    image: jaegertracing/all-in-one:1.66.0
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "4317:4317"
      - "16686:16686"
    networks:
      - api-design

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9091:8080"
      - "9090:9090"
    volumes:
      - ./deployment/docker-compose/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - api-design

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/tracing-dashboard.json
    volumes:
      - ./deployment/docker-compose/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./deployment/docker-compose/dashboard.json:/etc/grafana/provisioning/dashboards/tracing-dashboard.json
      - ./deployment/docker-compose/datasource.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    networks:
      - api-design


networks:
  api-design:
    driver: bridge
