services:
  openapi-editor:
    image: "swaggerapi/swagger-editor:v5.0.0-alpha.81-unprivileged"
    ports:
      - "6060:8080"
  openapi-linter:
    image: stoplight/spectral:6.15.1
    command: "lint /usr/src/openapi.yaml"
    volumes:
      - ./spectral:/usr/src/spectral
      - ./openapi.yaml:/usr/src/openapi.yaml
