{
 "title": "Tracing",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "traceId", "label": "Trace ID" }
  ]
 },
 "panels": [
  {
   "title": "Average Request Duration",
   "type": "gauge",
   "description": "Set Delivery Address Average Request Duration in the last 15 minutes",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(setAddressRequestDurations_Milliseconds_sum[5m])) / sum(rate(setAddressRequestDurations_Milliseconds_count[5m]))\n\n  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLA - 95% of Requests should be within 100ms",
   "type": "gauge",
   "description": "Gauge if an SLA is met or not.\nIn this case, that 95% of all the Set Delivery Address Request responds within 100ms.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(setAddressRequestDurations_Milliseconds_bucket{le=\"100\"}[5m])) by (job)/sum(rate(setAddressRequestDurations_Milliseconds_count[5m])) by (job)\n\n  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delivery Service",
   "type": "traces",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "query": "${traceId}" }
   ]
  },
  {
   "title": "Set Delivery Address Heatmap",
   "type": "heatmap",
   "description": "Occurrences of Response Times for the Set Delivery Address Request as Heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(setAddressRequestDurations_Milliseconds_bucket[5m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delivery Service",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    { "service": "delivery-deployment" }
   ]
  },
  {
   "title": "Customer Service",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    { "service": "customer-deployment" }
   ]
  },
  {
   "title": "Billing Service",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    { "service": "billing-deployment" }
   ]
  },
  {
   "title": "Address Validation Service",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    { "service": "address-validation-deployment" }
   ]
  },
  {
   "title": "Production Namespace Logs",
   "type": "logs",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "{namespace=\"production\"} |= \"${traceId}\""
    }
   ]
  }
 ]
}