apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: production
spec:
  mode: sidecar
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317

    exporters:
      otlp:
        endpoint: jaeger-collector.observability:4317
        tls:
          insecure: true  

    extensions:
      health_check: {}

    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp]
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: autoinject-instrumentation
  namespace: production
spec:
  exporter:
    endpoint: "http://0.0.0.0:4317"
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: '1'