#!/usr/bin/env groovy
pipeline {
    agent any

    parameters {
        booleanParam(name: 'verifyPacts', defaultValue: false, description: 'should this job just run to verify pacts from a consumer')
        booleanParam(name: 'deployOnly', defaultValue: false, description: 'should this job just run to deploy a version')
        string(name: 'deploymentVersion', defaultValue: 'latest', description: 'which version should be deployed')
    }

    options {
        disableConcurrentBuilds()
    }

    environment {
        SNAPSHOT_VERSION = readMavenPom().getVersion()
        LAST_COMMIT_MESSAGE = "${currentBuild.changeSets.size() == 0 ? 'update version to ' : currentBuild.changeSets[currentBuild.changeSets.size() - 1].items.length == 0 ? 'update version to ' : currentBuild.changeSets[currentBuild.changeSets.size() - 1].items[currentBuild.changeSets[currentBuild.changeSets.size() - 1].items.length - 1].msg}"
        PERFORM_RELEASE = "${env.SNAPSHOT_VERSION.contains('-SNAPSHOT') && env.BRANCH_NAME == 'main' && !env.LAST_COMMIT_MESSAGE.startsWith('update version to ')}"
        RELEASE_VERSION = "${env.SNAPSHOT_VERSION.contains('-SNAPSHOT') ? env.SNAPSHOT_VERSION.substring(0, env.SNAPSHOT_VERSION.lastIndexOf('-SNAPSHOT')) : SNAPSHOT_VERSION}"
        VERSION = "${env.BRANCH_NAME == 'main' && !env.LAST_COMMIT_MESSAGE.startsWith('update version to ') ? env.RELEASE_VERSION : env.SNAPSHOT_VERSION}"
        ROOT_DIRECTORY = "${params.verifyPacts == true && env.BRANCH_NAME == 'main' && env.SNAPSHOT_VERSION.endsWith("-SNAPSHOT") ? 'target/checkout' : '.'}"
        STAGE = "${env.BRANCH_NAME == 'main' ? 'prod' : 'test'}"
        DEPLOYMENT_VERSION = "${params.deploymentVersion != 'latest' ? params.deploymentVersion : env.VERSION}"
    }

    triggers {
        pollSCM("* * * * *")
        GenericTrigger(
            genericRequestVariables: [
                [key: 'stage', regexpFilter: ''],
                [key: 'verifyPacts', regexpFilter: ''],
                [key: 'deployOnly', regexpFilter: ''],
                [key: 'deploymentVersion', regexpFilter: '']
            ],

            causeString: 'Triggered by web hook',

            token: 'delivery-service',

            printContributedVariables: true,
            printPostContent: true,

            silentResponse: false,

            regexpFilterText: '$stage',
            regexpFilterExpression: ".*${(env.BRANCH_NAME == 'main' ? 'prod' : 'test')}.*"
        )
    }

    stages {
        stage ('Compile') {
            when {
                anyOf {
                    not {
                        branch 'main'
                    }
                    environment name: 'PERFORM_RELEASE', value: 'true'
                    expression {
                        params.verifyPacts == true
                    }
                }
                expression {
                    params.deployOnly == false
                }
            }
            steps {
                echo "Building version ${env.VERSION}"
                script {
                    if (params.verifyPacts == true && env.BRANCH_NAME == 'main' && env.SNAPSHOT_VERSION.endsWith("-SNAPSHOT")) {
                        int previousRevision = Integer.parseInt(env.RELEASE_VERSION.substring(env.RELEASE_VERSION.lastIndexOf(".") + 1)) - 1
                        if (previousRevision >= 0) {
                            previousVersion = RELEASE_VERSION.substring(0, env.RELEASE_VERSION.lastIndexOf(".")) + "." + previousRevision
                            sh "mvn scm:checkout -DscmVersionType=tag -DscmVersion=${previousVersion}"
                            echo "Testing against version ${previousVersion}"
                        }
                    } else if (env.PERFORM_RELEASE.equals('true') && !env.RELEASE_VERSION.equals(env.SNAPSHOT_VERSION)) {
                        sh "mvn versions:set -DnewVersion=${env.RELEASE_VERSION} -B"
                    }
                }
                sh """
                    cd ${ROOT_DIRECTORY}
                    mvn clean test-compile -B
                """
            }
        }
        stage ('Test') {
            when {
                anyOf {
                    not {
                        branch 'main'
                    }
                    environment name: 'PERFORM_RELEASE', value: 'true'
                    expression {
                        params.verifyPacts == true
                    }
                }
                expression {
                    params.deployOnly == false
                }
            }
            steps {
                sh """
                    cd ${ROOT_DIRECTORY}
                    mvn test -DpactBroker.url=http://pact:9292 -Dpact.verifier.publishResults=true -Dpact.tag=${params.verifyPacts ? 'pending-' + env.STAGE : env.STAGE} -B
                """
            }
        }
        stage ('Upload pacts') {
            when {
                anyOf {
                    not {
                        branch 'main'
                    }
                    environment name: 'PERFORM_RELEASE', value: 'true'
                }
                expression {
                    params.verifyPacts == false && params.deployOnly == false
                }
            }
            steps {
                sh "mvn pact:publish -DpactBroker.url=http://pact:9292  -Dpact.verifier.publishResults=true  -Dpact.consumer.tags=pending-${env.STAGE} -B"
            }
        }
        stage ('Package') {
            when {
                anyOf {
                    not {
                        branch 'main'
                    }
                    environment name: 'PERFORM_RELEASE', value: 'true'
                }
                expression {
                    params.verifyPacts == false && params.deployOnly == false
                }
            }
            steps {
                sh 'mvn package meecrowave:bundle -Dservice.name=delivery-service -DskipTests -B'
            }
        }
        stage ('Push') {
            when {
                anyOf {
                    not {
                        branch 'main'
                    }
                    environment name: 'PERFORM_RELEASE', value: 'true'
                }
                expression {
                    params.verifyPacts == false && params.deployOnly == false
                }
            }
            steps {
                script {
                    if (env.PERFORM_RELEASE.equals('true') && !env.RELEASE_VERSION.equals(env.SNAPSHOT_VERSION)) {
                        sh """
                            sshpass -p 'jenkins' ssh -o "StrictHostKeyChecking=no" -p 2222 -q jenkins@prod 'mkdir -p ~/artifacts/delivery-service/${env.RELEASE_VERSION}/'
                            sshpass -p 'jenkins' scp -o "StrictHostKeyChecking=no" -P 2222 -q target/delivery-service*.zip jenkins@prod:/config/artifacts/delivery-service/${env.RELEASE_VERSION}/
                            git config --global user.name 'Jenkins'
                            git config --global user.email 'ci@openknowledge.de'
                            mvn scm:checkin -Dmessage='release of version ${env.RELEASE_VERSION}' -B
                            mvn scm:tag -Dtag=${env.RELEASE_VERSION} -B
                        """
                        int nextRevision = Integer.parseInt(env.RELEASE_VERSION.substring(env.RELEASE_VERSION.lastIndexOf(".") + 1)) + 1
                        nextVersion = RELEASE_VERSION.substring(0, env.RELEASE_VERSION.lastIndexOf(".")) + "." + nextRevision + "-SNAPSHOT"
                        sh "mvn versions:set scm:checkin -DnewVersion=${nextVersion} -Dmessage='update version to ${nextVersion}' -B"
                    } else {
                        sh """
                            sshpass -p 'jenkins' ssh -o "StrictHostKeyChecking=no" -p 2222 -q jenkins@test 'mkdir -p ~/artifacts/delivery-service/${env.SNAPSHOT_VERSION}/'
                            sshpass -p 'jenkins' scp -o "StrictHostKeyChecking=no" -P 2222 -q target/delivery-service*.zip jenkins@test:/config/artifacts/delivery-service/${env.SNAPSHOT_VERSION}/
                        """
                    }
                }
            }
        }
        stage ('Deploy') {
            when {
                expression {
                    script {
                        def deploy = sh script: "pact-broker can-i-deploy --pacticipant delivery-service --version ${env.DEPLOYMENT_VERSION} --to ${env.STAGE} --broker-base-url pact:9292", returnStatus: true
                        return deploy == 0
                    }
                }
                anyOf {
                    not {
                        branch 'main'
                    }
                    environment name: 'PERFORM_RELEASE', value: 'true'
                    expression {
                        params.deployOnly == true
                    }
                }
            }
            steps {
                script {
                    if (env.STAGE == 'prod') {
                        sh "sshpass -p 'jenkins' ssh -o 'StrictHostKeyChecking=no' -p 2222 -q jenkins:jenkins@prod '[ -f ~/delivery-service-distribution/bin/meecrowave.sh ] && ~/delivery-service-distribution/bin/meecrowave.sh stop && rm -rf ~/delivery-service-distribution/; unzip ~/artifacts/delivery-service/${env.DEPLOYMENT_VERSION}/delivery-service-meecrowave-distribution.zip -d ~/; nohup ~/delivery-service-distribution/bin/meecrowave.sh start --http=8083'"
                    } else {
                        sh "sshpass -p 'jenkins' ssh -o 'StrictHostKeyChecking=no' -p 2222 -q jenkins:jenkins@test '[ -f ~/delivery-service-distribution/bin/meecrowave.sh ] && ~/delivery-service-distribution/bin/meecrowave.sh stop && rm -rf ~/delivery-service-distribution/; unzip ~/artifacts/delivery-service/${env.DEPLOYMENT_VERSION}/delivery-service-meecrowave-distribution.zip -d ~/; export JAVAX_PERSISTENCE_JDBC_URL=jdbc:postgresql://delivery-db-test:5432/postgres; nohup ~/delivery-service-distribution/bin/meecrowave.sh start --http=8083'"
                    }
                    sh "curl -H 'Content-Type: application/json' -X PUT http://pact:9292/pacticipants/delivery-service/versions/${env.DEPLOYMENT_VERSION}/tags/${env.STAGE}"
                    sh "curl -X DELETE http://pact:9292/pacticipants/delivery-service/versions/${env.DEPLOYMENT_VERSION}/tags/pending-${env.STAGE}"
                }
            }
        }
    }
}
